GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/info/

###
GET  http://localhost:3001/api/persons/1

###
GET  http://localhost:3001/api/persons/64d63c45e3583a8cc2dd1ba8

###
DELETE http://localhost:3001/api/persons/64d63c1eb5a442d2a637326f

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name":"Sa",
    "number": 21
}

###
PUT http://localhost:3001/api/persons/64d63c45e3583a8cc2dd1ba8
content-type: application/json

{
    "name":"Arto Hellas",
    "number": 218
}