GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/info/

###
GET  http://localhost:3001/api/persons/1

###
GET  http://localhost:3001/api/persons/5

###
DELETE http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name":"wes",
    "number": 21
}

###
GET http://localhost:3001/api/persona/5